### ISSUE TITLE
Swagger lack of some meta parameters

### ISSUE THREAD

**Issue by robertstrz** [ppetzold/nestjs-paginate#922] opened 2024-05-20 06:32 UTC
Hi,
I am wondering why Swagger is missing some of the parameters from meta property. In decorator there are only 2 properties in meta object defined. I am using OpenAPI generator to generate client so those are missing in a client definition.
```javascript
    meta: {
        itemsPerPage: number
        totalItems: number
        currentPage: number
        totalPages: number
        sortBy: SortBy<T>
        searchBy: Column<T>[]
        search: string
        select: string[]
        filter?: {
            [column: string]: string | string[]
        }
    }
 ```
 
 
 Swagger decorator
 ```javascript return applyDecorators(
        ApiExtraModels(PaginatedDocumented, dataDto),
        ApiOkResponse({
            schema: {
                allOf: [
                    { $ref: getSchemaPath(PaginatedDocumented) },
                    {
                        properties: {
                            data: {
                                type: 'array',
                                items: { $ref: getSchemaPath(dataDto) },
                            },
                            meta: {
                                properties: {
                                    select: {
                                        type: 'array',
                                        items: {
                                            type: 'string',
                                            enum: paginatedConfig?.select,
                                        },
                                    },
                                    filter: {
                                        type: 'object',
                                        properties: Object.keys(cols).reduce(
                                            (acc, key) => {
                                                acc[key] = {
                                                    oneOf: [
                                                        {
                                                            type: 'string',
                                                        },
                                                        {
                                                            type: 'array',
                                                            items: {
                                                                type: 'string',
                                                            },
                                                        },
                                                    ],
                                                }
                                                return acc
                                            },
                                            {} as Record<string, SchemaObject | ReferenceObject>
                                        ),
                                    },
                                },
                            },
                        },
                    },
                ],```

**Comment by Helveg** [comment] 2024-05-20 20:58
I'm not sure how that decorator is supposed to work, but there seems to be additional properties in the `{ $ref: getSchemaPath(PaginatedDocumented) }` part. Can you show with a reproducer when these meta properties are missing?

**Comment by robertstrz** [comment] 2024-05-21 16:09
Sure,
so as I mentionted I am generating client with openapi-tools

```
import { OpenApiNestFactory } from 'nest-openapi-tools'
...

		await OpenApiNestFactory.configure(
			app,
			new DocumentBuilder()
				.setTitle('Core API')
				.addServer('NEXT_PUBLIC_BACKED_API_URL', 'staging', {
					variable: { default: '3.0' },
				})
				.addBearerAuth(),
			{
				webServerOptions: {
					enabled: true,
					path: 'docs',
				},
				fileGeneratorOptions: {
					enabled: true,
					outputFilePath: './openapi.yaml', // or ./openapi.json
				},
				clientGeneratorOptions: {
					enabled: false,
					type: 'typescript-fetch',
					outputFolderPath: '../../web/typescript-api-client/src',
					additionalProperties:
						'apiPackage=clients,modelPackage=models,withoutPrefixEnums=true,withSeparateModelsAndApi=true',
					openApiFilePath: './openapi.yaml',
					skipValidation: true, // optional, false by default
				},
			},
			{
				operationIdFactory: (c: string, method: string) => method,
			},
		)
```

If I open swagger documentation in browser then it shows that indeed totalItems is in response

![image](https://github.com/ppetzold/nestjs-paginate/assets/5371568/a57adafb-873d-41e8-927b-ac257fc26461)


But when I am generating client from openapi.yaml some properties are missing from generated client and only 2 of them are shown filter and select. 

Quick workaround for that for me right now is that I have taken your decorator and added missing property by hand

```
	return applyDecorators(
		ApiExtraModels(PaginatedDocumented, dataDto),
		ApiOkResponse({
			schema: {
				allOf: [
					{ $ref: getSchemaPath(PaginatedDocumented) },
					{
						properties: {
							data: {
								type: 'array',
								items: { $ref: getSchemaPath(dataDto) },
							},
							meta: {
								properties: {
									select: {
										type: 'array',
										items: {
											type: 'string',
											enum: paginatedConfig?.select,
										},
									},
									totalItems: {
										type: 'number',
									},
									filter: {
										type: 'object',
										properties: Object.keys(cols).reduce(
											(acc, key) => {
												acc[key] = {
													oneOf: [
														{
															type: 'string',
														},
														{
															type: 'array',
															items: {
																type: 'string',
															},
														},
													],
												}
												return acc
											},
											{} as Record<string, SchemaObject | ReferenceObject>,
										),
									},
								},
							},
						},
					},
				],
			},
		}),
	)
```

Below is part of openapi.yaml that is generated automatically when decorator from you package is used. Based on this file I am generating typescript-fetch client.

```
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/PaginatedDocumented"
                  - properties:
                      data:
                        type: array
                        items:
                          $ref: "#/components/schemas/MyEntity"
                      meta:
                        properties:
                          select:
                            type: array
                            items:
                              type: string
                          filter:
                            type: object
                            properties:
                              name:
                                oneOf:
                                  - type: string
                                  - type: array
                                    items:
                                      type: string

**Comment by Helveg** [comment] 2024-05-21 20:03
Hmm thanks for you detailed report. Do you think you could create a quick repository with some steps for me to follow to generate the same things you're speaking of? That way I can follow the steps and make changes to arrive at the same outcome as your workaround!

**Comment by vsamofal** [comment] 2024-05-21 22:12
I didn't get an issue tbh, as far as I understand swagger UI looks ok, but your code that exports Swagger and generates a client, doesn't generate a proper one. ? 


if yes, can you download a spec file from swagger UI and compare it 

@robertstrz

**Comment by Helveg** [comment] 2024-06-05 11:32
Closing due to lack of reproducer and author response. Feel free to reopen so we can pick this back up :)

**Closed by Helveg** 2024-06-05 11:32 UTC
