### ISSUE TITLE
ERROR [ExceptionsHandler] syntax error at or near "Object"

### ISSUE THREAD

**Issue by mohdalali** [ppetzold/nestjs-paginate#585] opened 2023-04-13 01:12 UTC
I'm getting this error whenever I try to use the paginate function. Below find below the code.

```
import {
  CreateDateColumn,
  UpdateDateColumn,
  DeleteDateColumn,
  Entity,
  Column,
  PrimaryGeneratedColumn,
} from 'typeorm';
import { Exclude } from 'class-transformer';

@Entity()
export class User {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;

  @Column({
    length: 30,
    unique: true,
  })
  username: string;

  @Column({ unique: true })
  email: string;

  @Column({
    length: 15,
    unique: true,
    nullable: true,
  })
  phone: string;

  @Column({ select: false })
  password: string;

  @CreateDateColumn({ name: 'created_at' })
  createdAt: Date;

  @UpdateDateColumn({ name: 'updated_at' })
  updatedAt: Date;

  @DeleteDateColumn({ name: 'deleted_at' })
  @Exclude()
  deletedAt?: Date;
}
```

```
import {
  Controller,
  Get,
  Post,
  Body,
  Patch,
  Param,
  Delete,
  UseInterceptors,
  ClassSerializerInterceptor,
} from '@nestjs/common';
import { UsersService } from './users.service';
import { CreateUserDto } from './dto/create-user.dto';
import { UpdateUserDto } from './dto/update-user.dto';
import { Paginated, Paginate, PaginateQuery } from 'nestjs-paginate';
import { User } from './entities/user.entity';

@UseInterceptors(ClassSerializerInterceptor)
@Controller('users')
export class UsersController {
  constructor(private readonly usersService: UsersService) {}

  @Post()
  create(@Body() createUserDto: CreateUserDto) {
    return this.usersService.create(createUserDto);
  }

  @Get()
  findAll(@Paginate() query: PaginateQuery): Promise<Paginated<User>> {
    return this.usersService.findAll(query);
  }

  @Get(':id')
  findOne(@Param('id') id: string) {
    return this.usersService.findOne(+id);
  }

  @Patch(':id')
  update(@Param('id') id: string, @Body() updateUserDto: UpdateUserDto) {
    return this.usersService.update(+id, updateUserDto);
  }

  @Delete(':id')
  remove(@Param('id') id: string) {
    return this.usersService.remove(+id);
  }
}
```

```
import { Injectable } from '@nestjs/common';
import { CreateUserDto } from './dto/create-user.dto';
import { UpdateUserDto } from './dto/update-user.dto';
import { Repository } from 'typeorm';
import { InjectRepository } from '@nestjs/typeorm';
import {
  FilterOperator,
  FilterSuffix,
  Paginated,
  paginate,
  PaginateQuery,
} from 'nestjs-paginate';
import { User } from './entities/user.entity';

@Injectable()
export class UsersService {
  constructor(
    @InjectRepository(User)
    private readonly usersRepository: Repository<User>,
  ) {}

  create(createUserDto: CreateUserDto) {
    return this.usersRepository.save(createUserDto);
  }

  findAll(query: PaginateQuery): Promise<Paginated<User>> {
    return paginate(query, this.usersRepository, {
      sortableColumns: [
        'name',
        'username',
        'email',
        'phone',
        'createdAt',
        'updatedAt',
      ],
      nullSort: 'last',
      defaultSortBy: [['id', 'DESC']],
      searchableColumns: ['name', 'username', 'email', 'phone'],
      select: [
        'id',
        'name',
        'username',
        'email',
        'phone',
        'createdAt',
        'updatedAt',
      ],
      filterableColumns: {
        name: [FilterOperator.EQ, FilterSuffix.NOT],
      },
    });
  }

  findOne(id: number) {
    return this.usersRepository.findOneBy({ id });
  }

  update(id: number, updateUserDto: UpdateUserDto) {
    return this.usersRepository.update(id, updateUserDto);
  }

  remove(id: number) {
    return this.usersRepository.softDelete({ id });
  }
}
```

What may be causing this issue?

**Comment by mohdalali** [comment] 2023-04-13 01:13
This is the error I'm getting.

```
[Nest] 3820  - 04/12/2023, 6:09:09 PM   ERROR [ExceptionsHandler] syntax error at or near "Object"
QueryFailedError: syntax error at or near "Object"
    at PostgresQueryRunner.query (C:\Users\user\Projects\alshara\api\src\driver\postgres\PostgresQueryRunner.ts:299:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at SelectQueryBuilder.loadRawResults (C:\Users\user\Projects\alshara\api\src\query-builder\SelectQueryBuilder.ts:3782:25)
    at SelectQueryBuilder.executeEntitiesAndRawResults (C:\Users\user\Projects\alshara\api\src\query-builder\SelectQueryBuilder.ts:3537:26)
    at SelectQueryBuilder.getManyAndCount (C:\Users\user\Projects\alshara\api\src\query-builder\SelectQueryBuilder.ts:1872:36)
    at paginate (C:\Users\user\Projects\alshara\api\node_modules\nestjs-paginate\src\paginate.ts:263:32)
```

**Comment by ppetzold** [comment] 2023-04-13 06:47
can you enable typeorm logging and print the SQL query as well as your URL query params here?

**Comment by mohdalali** [comment] 2023-04-14 09:21
> can you enable typeorm logging and print the SQL query as well as your URL query params here?

Thanks for your response. Below is the SQL query received by TypeORM logging.

```
query: SELECT "__root"."id" AS "__root_id", "__root"."name" AS "__root_name", "__root"."username" AS "__root_username", "__root"."email" AS "__root_email", "__root"."phone" AS "__root_phone", "__root"."created_at" AS "__root_created_at", "__root"."updated_at" AS "__root_updated_at" FROM "user" "__root" WHERE "__root"."deleted_at" IS NULL ORDER BY "__root_id" [object Object] LIMIT 20
query failed: SELECT "__root"."id" AS "__root_id", "__root"."name" AS "__root_name", "__root"."username" AS "__root_username", "__root"."email" AS "__root_email", "__root"."phone" AS "__root_phone", "__root"."created_at" AS "__root_created_at", "__root"."updated_at" AS "__root_updated_at" FROM "user" "__root" WHERE "__root"."deleted_at" IS NULL ORDER BY "__root_id" [object Object] LIMIT 20
error: error: syntax error at or near "Object"
[Nest] 14700  - 04/14/2023, 2:19:07 AM   ERROR [ExceptionsHandler] syntax error at or near "Object"
```

Not sure why I see [object Object] towards the end, is this normal? No query params in the URL.

**Comment by ppetzold** [comment] 2023-04-14 09:28
that's odd, can you those lines to check what contains the object?

https://github.com/ppetzold/nestjs-paginate/blob/master/src/paginate.ts#L174-L188

**Comment by ppetzold** [comment] 2023-04-14 09:28
default sort etc has coverage, so should show if lib has any bug 🤔

**Comment by mohdalali** [comment] 2023-04-14 09:40
It seems that its from the select property in the PaginateConfig, whenever I have it in the config it shows this error.

```
      select: [
        'id',
        'name',
        'username',
        'email',
        'phone',
        'createdAt',
        'updatedAt',
      ],
```

Otherwise, it works fine:
```
query: SELECT "__root"."id" AS "__root_id", "__root"."name" AS "__root_name", "__root"."username" AS "__root_username", "__root"."email" AS "__root_email", "__root"."phone" AS "__root_phone", "__root"."created_at" AS "__root_created_at", "__root"."updated_at" AS "__root_updated_at", "__root"."deleted_at" AS "__root_deleted_at" FROM "user" "__root" WHERE "__root"."deleted_at" IS NULL ORDER BY "__root"."id" DESC NULLS LAST LIMIT 20
query: SELECT COUNT(1) AS "cnt" FROM "user" "__root" WHERE "__root"."deleted_at" IS NULL
```

**Comment by ppetzold** [comment] 2023-04-14 09:49
umm, could you submit a PR with a test case which replicates the error?

**Comment by harmoney-franck** [comment] 2023-04-17 04:47
I'm facing the same issue, without select it works, but adding select like `select: ['id', 'email', 'createdAt']` 
```
"message":"syntax error at or near \"Object\"","stack":["QueryFailedError: syntax error at or near \"Object\"\n    at PostgresQueryRunner.query (/app/src/driver/postgres/PostgresQueryRunner.ts:299:19)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at SelectQueryBuilder.loadRawResults (/app/src/query-builder/SelectQueryBuilder.ts:3782:25)\n    at SelectQueryBuilder.executeEntitiesAndRawResults (/app/src/query-builder/SelectQueryBuilder.ts:3537:26)\n    at SelectQueryBuilder.getManyAndCount (/app/src/query-builder/SelectQueryBuilder.ts:1872:36)\n    at paginate (/app/node_modules/nestjs-paginate/src/paginate.ts:263:32)"]
```

**Comment by ppetzold** [comment] 2023-04-17 08:43
would appreciate PR with test case which reproduces the error. `select` actually has coverage with sqlite and postgres

**Comment by harmoney-franck** [comment] 2023-04-17 23:25
@ppetzold, I narrowed down my issue: on my entity I have the following column:
```ts
  @CreateDateColumn()
  createdAt: Date;
``` 

It seems that it can't parse Date type as it returns the expected fields without querying that field, is there a way to fix it (other than changing the type to string)?

**Comment by ppetzold** [comment] 2023-04-18 07:24
is `Object` being written to the select part of the query or again to ORDER BY as for @mohdalali ?

**Comment by ppetzold** [comment] 2023-04-18 07:24
pls also print query + conf + sql here

**Comment by harmoney-franck** [comment] 2023-04-19 04:16
Query log: 
```bash
"message":"Paginating users Query: {\"page\":1,\"limit\":50,\"select\":[\"id\",\"email\",\"preferredName\",\"createdAt\"],\"path\":\"http://127.0.0.1:3002/api/users/all-users\"}","timestamp":"2023-04-19 04:10:59.5959+00:00"}
```

Config: 
```ts
paginate(query, this.userRepository, {
      sortableColumns: ['createdAt'],
      nullSort: 'last',
      defaultSortBy: [['createdAt', 'DESC']],
      searchableColumns: ['id', 'email', 'preferredName'],
      select: ['id', 'email', 'preferredName', 'createdAt'],
      defaultLimit: 50,
    });
```

error: 
```bash
{"context":"ExceptionsHandler","level":"error",
"message":"syntax error at or near \"Object\"",
"stack":["QueryFailedError: syntax error at or near \"Object\"\n    
at PostgresQueryRunner.query (/app/src/driver/postgres/PostgresQueryRunner.ts:299:19)\n    
at processTicksAndRejections (node:internal/process/task_queues:95:5)\n   
at SelectQueryBuilder.loadRawResults (/app/src/query-builder/SelectQueryBuilder.ts:3787:25)\n    
at SelectQueryBuilder.executeEntitiesAndRawResults (/app/src/query-builder/SelectQueryBuilder.ts:3542:26)\n    
at SelectQueryBuilder.getManyAndCount (/app/src/query-builder/SelectQueryBuilder.ts:1872:36)\n    
at paginate (/app/node_modules/nestjs-paginate/src/paginate.ts:263:32)"],"timestamp":"2023-04-19 04:10:59.5959+00:00"}
```

endpoint: `/api/users/all-users?page=1&limit=50&search=&select=id%2Cemail%2CpreferredName%2CcreatedAt`

**Comment by harmoney-franck** [comment] 2023-04-20 20:50
@ppetzold Any idea on what could be the root cause?

**Comment by ppetzold** [comment] 2023-04-21 05:10
The comma in the select query is url encoded. Shouldn't be. Could this cause it? 🤔

**Comment by harmoney-franck** [comment] 2023-04-21 06:15
I've tried not including select in the client query and only setting it on the config but ended up with the same result... 

FYI We're using React and RTK Query on the front end.

**Comment by ppetzold** [comment] 2023-04-21 06:52
Can you try to build a test case in paginate.spec.ts which reproduces the error and submit as  PR?

**Comment by harmoney-franck** [comment] 2023-04-23 22:28
@ppetzold I created the PR

**Comment by harmoney-franck** [comment] 2023-04-23 23:19
Seems like removing ` nullSort: 'last',` fixes the issue

**Comment by ppetzold** [comment] 2023-04-30 16:15
interesting, seems like the issue is with typeorm then

**Comment by ppetzold** [comment] 2023-04-30 16:16
Will close this then

**Closed by ppetzold** 2023-04-30 16:16 UTC
